### ISSUE TITLE
PyQtGraph AttributeError: module 'pyqtgraph.colormap' has no attribute 'get'

### ISSUE THREAD

**Issue by mlerotic** [mlerotic/spectromicroscopy#6] opened 2021-11-15 10:04 UTC
On development branch I get attribute error when running mantis:
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python37\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\__main__.py", line 17, in <module>
    sys.exit(main())
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\__main__.py", line 13, in main
    mantis_qt.main()  # Open the GUI
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 17238, in main
    frame = MainFrame()
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 16472, in __init__
    self.initUI()
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 16496, in initUI
    self.page0 = PageLoadData(self.common, self.data_struct, self.stk)
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 14849, in __init__
    self.initUI(common, data_struct, stack)
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 14868, in initUI
    self.absimgfig = ImgFig(self, self.canvas)
  File "D:\Work\Python\Mantis\Mantis_scr\mantis_xray\mantis_qt.py", line 16351, in __init__
    cm = pg.colormap.get(self.map, source="matplotlib")
AttributeError: module 'pyqtgraph.colormap' has no attribute 'get'

Running latest version of pyqtgraph 0.12.3

**Comment by Grumium** [comment] 2021-11-15 10:51
The current development branch relies on pyqtgraph 0.12.1 as defined in the setup.py file.

`install_requires=['numpy', 'scipy','matplotlib','h5py','Pillow','lxml','pyqtgraph==0.12.1','scikit-image','PyQt5==5.15.2']`

However, I cannot reproduce the issue with pyqtgraph 0.12.3
Could you please check your package version via
`import pyqtgraph`
`print(pyqtgraph.__version__)`
?

**Comment by Grumium** [comment] 2021-11-15 11:37
Fixed in https://github.com/mlerotic/spectromicroscopy/commit/846c0f58ff697068406013ed1c4c42a9a679d34f

**Closed as completed by Grumium** 2021-11-15 11:37 UTC
