### ISSUE TITLE
Unable to proceed to PCA after loading I0 file from "I0 from file" in Mantis

### ISSUE THREAD

**Issue by soilkoya** [mlerotic/spectromicroscopy#29] opened 2024-11-21 07:40 UTC
Hello,

I am encountering an issue while using Mantis. After successfully loading the I0 file using the "I0 from file" option, I am unable to proceed to the PCA (Principal Component Analysis) step.

Here are the steps I followed:

Opened Mantis and loaded my data.
Selected "I0 from file" and loaded the I0 file.
Attempted to proceed to PCA, but it seems that the software does not allow me to move to the PCA step.

Could this be an operational mistake or  in the software? 
Thank you for the amazing analysis software!

**Comment by Grumium** [comment] 2024-12-14 21:17
Hi. 
I am sorry for the late reply. I followed your steps and I cannot reproduce your issue.
Please provide more information about the exact version of the program, packages and post potential error messages.
How did you create the I0 file? Are you sure that the I0 file has been loaded successfully?

**Comment by Grumium** [comment] 2024-12-25 04:22
Any news? Please try https://github.com/mlerotic/spectromicroscopy/commit/32e1ac21fca24cf431e6262292571a01f28840b4 and report if this fixed your issue.

**Comment by soilkoya** [comment] 2024-12-25 05:06
Sorry, I was too busy to notice your comment. 32e1ac2  solved the problem. 
Thanks for a great tool!!.

**Comment by Grumium** [comment] 2024-12-25 08:37
You are welcome. It seems to me like the issue occurred when you tried to load an I0 spectrum in a format other than *.csv, possibly *.xas. The bug causing this problem has been fixed in the commit linked above.
Merry Christmas!

**Closed as completed by Grumium** 2024-12-25 08:37 UTC
